api/index.js
client/storage/payments.js

>adds functions to check if network token is registered on raiden
>adds function to register network token
>registers token on PN node start up

Join a token network

---

docker-compose.yaml
network/web3bridge.js
scripts/await-contracts-docker.js
scripts/deploy-sites-docker.sh

* Fixed error related to an incorrectly set chain id
* Fixed container name in `deploy-sites-docker.sh`
* Improved Point Network node entrypoint script
* Added debug logging in `web3bridge.js`

Fix dev docker compose

---

client/zweb/renderer/index.js
example/email.z/views/index.zhtml
example/email.z/views/js/email.js

* Added a Twig function `storage_get_by_ikv`
* Obtained, sanitized and parsed the contract ABI JSON
* Instantiated the contract with the parsed ABI object

Load email contract abi

---

client/zweb/renderer/index.js
example/email.z/views/compose.zhtml
network/web3bridge.js
resources/demo-docker/config.test2.json
tests/email.validation.spec.js
truffle/contracts/Identity.sol

* Added email identity management capabilities to the `Identity` contract
* Added `web3bridge` and `twig` functions for obtaining email identity by owner address

User friendly email addresses

---

client/zweb/deployer/index.js
example/blog.z/contracts/Blog.sol
example/email.z/contracts/Email.sol
example/twitter.z/contracts/Twitter.sol
package-lock.json
package.json

> adds function to fetch solidity file version
> checks for contract dependencies in contract and node modules folder
> injects dependencies and compile contract

idea for using multiple versions of solc

---

README.md
api/controllers/StorageController.js
client/storage/index.js
client/zweb/deployer/index.js
db/models/chunk.js
db/models/directory.js
db/models/file.js
package-lock.json
scripts/db/playground.js

Please review if the place where I'm doing the re-assignment is the appropriate place.
According to what I understood after reviewing several parts of the source code, we use `File.localPath` and `Directory.localPath` to set the original sources of the files and directories being read, respectively. At the moment we want to upload a file via `storage.putFile`, we use `File.localPath` to `File.chunkify` the file, which is the expected behavior. However, after chunkifying the file, we want to `model.save` it to our LevelDB database. In this step, `File.localPath` needs to be set to the newly created chunk file, which is named `'chunk_id' + File.id`, where `File.id` is the `id` given to the file by `chunkify`, instead of using the original file's path name.

Fix #55: The localPath of all the files on the node should be set to the nodes storage layer.

---

api/api_routes.js
api/controllers/IdentityController.js

Added endpoints:
[`GET /v1/api/identity/identityToOwner/{identity}`](https://pointnetwork.github.io/api/#tag/Identity)
[`GET /v1/api/identity/ownerToIdentity/{owner}`](https://pointnetwork.github.io/api/#tag/Identity/paths/~1ownerToIdentity~1%7Bowner%7D/get)

Added endpoints for identity management.

---

.eslintrc.json
api/sockets/ZProxySocketController.js
example/hello.z/public/index.html
example/store.z/src/@types/index.d.ts
example/store.z/src/App/Context.tsx
example/store.z/src/App/index.css
example/store.z/src/App/index.tsx
example/store.z/src/Products/Context.tsx
example/store.z/watch.docker.js
network/web3bridge.js

* unified ws messaging protocol
* updated `store.z`

Store.z contract event unsubscription

---

api/index.js
api/sockets/NodeSocketController.js
api/sockets/ZProxySocketController.js
db/model.js
point

I've chosen the simplest solution since this is a temporary fix anyway. But it works fine: in case of our conflict, 1 retry attempt is enough.

Sqlite fix unique violation

---

example/pointsocial.z/src/components/comments/Comments.jsx
example/pointsocial.z/src/components/post/Post.jsx

In the Post component the comments count became a state variable which is updated by comments component when a new comment is posted.

Updating comments count when a new comment is posted

---

example/hello.z/public/index.html

Updates the `value` string in hello.z Zapp.
Related story - [here](https://trello.com/c/HCBIKEvh/40-include-a-simple-form-to-helloz-to-update-the-storage-value-in-the-smart-contract)

Update value in smart contract through the hello.z Zapp

---

client/zweb/renderer/index.js
package-lock.json
package.json
point

@tankakatan Please be sure to build a new docker image and update tags

Implement new lockfile logic and fix logger issue

---

package.json
scripts/build-sqlite3-for-all-platforms.sh

This change builds necessary sqlite3 artifacts required by the packed executable by vercel/pkg.

Add script to build sqlite3 for all platforms

---

.github/workflows/pkg.yaml
package-lock.json
package.json

It will listen for tags with the format v* to create a new release.

Add workflow to create a  new release and attached packaged application for linux, mac and win

---

package-lock.json
package.json
src/client/storage/uploader.ts
src/db/makeMigrationsEntrypoint.ts
src/db/model.js
src/db/models/index.ts
src/index.ts
src/util/migrate.ts

Add script for sequelize-mig to create migrations

Generate migrations from models

---

src/client/storage/index-arlocal.js
src/client/storage/index.js
src/index.ts
src/network/blockchain.js
src/util/index.ts
src/util/makeSurePathExists.ts
src/util/readFileByPath.ts
src/util/statAsync.ts

Related to this issue:
https://github.com/vercel/pkg/issues/1505

Not use stat function from fs-promises since it's broken for pkg library

---

src/api/controllers/BlockchainController.ts

Added support for the RPC method `eth_requestAccounts`, defined in [EIP-1102](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1102.md), as it is supported by MetaMask and it's mentioned in their "getting started" guide, which means we can expect it to be present in many dApps.
_PS: This PR builds on top of [the one for PN-99](https://github.com/pointnetwork/pointnetwork/pull/329); so, if that one is merged before this one, I'll change the base branch._

PN-106 eth_requestAccounts

---

internal/explorer.point/public/identities.zhtml

Using events to fetch identities.

Improving performance of identities page

---

src/api/controllers/IdentityController.js
src/network/blockchain.js

Fix import and ESLint warning.

Fix get referral code import

---

hardhat/contracts/Identity.sol
hardhat/scripts/deploy.ts
scripts/start-local.sh

Create a devmode in identity contract to bypass validations when needed, such as e2e tests and zappdev environment. (PZ-199).

Dev mode in identity contract

---

resources/config/devlocal_template.yaml
resources/config/visitlocal_template.yaml

This PR includes a small fix to the locale yaml files to accommodate the new multi-chain format

Fix devlocal and visitlocal template format

---

hardhat.config.js

This PR contains a small change to avoid hardhat deployment errors

Changed accounts parameter, included gas and gasPrice to avoid UNPREDICTABLE_GAS_LIMIT

---

hardhat.config.js

Fix a problem with local env deployment when ynet private key is not set.

fix local deploy problem

---

src/api/controllers/WalletController.js

This PR contains a small change in WalletController to correctly call getBalance imported method

Small fix in WalletController to correctly call getBalance

---

package-lock.json
package.json
src/client/proxy/handlers/common.ts
src/network/providers/ethereum.js
src/util/cache.ts

After profiling the proxy functions related to get blockchain information are consuming at least 500ms each time. So I added a cache in the blockchain layer with a TTL of 20s.

Add cache to blockchain methods

---

src/core/log.js

It collects OS information for future debugging.

Add os information to first log

---

src/@types/index.d.ts
src/api/controllers/DeployController.js
src/client/zweb/deployer/index.js
src/core/deploy.js
src/index.ts

Added a new ikv entry when deploying a DApp to register which commit was deployed. The entry stores the last commit sha when deploying the DApp.

PZ 301 sha commit ikv entry

---

src/client/zweb/deployer/index.js

Validate the existence of mandatory entries in point.deploy.json.

Pz 290 improve deploy error msg

---

hardhat.config.js

Add optimizer and remove gas options for hardhat config to solve the problem of halting deployment of contracts with hardhat on YNet.

Fix hardhat gas problem with deployment

---

src/index.ts

Please refer to [PN-183](https://point-labs.atlassian.net/browse/PN-183) for context and to the companion [PR in Point Dashboard](https://github.com/pointnetwork/pointnetwork-dashboard/pull/339).

Exit process with custom codes

---

src/client/proxy/handlers/storage.ts

Allow to download files from rooDir listing page (PZ-408).

Remove extension from storage

---

src/client/proxy/handlers/common.ts
src/client/proxy/proxyUtils.ts
src/client/storage/index.ts
src/util/index.ts
src/util/storageIdValidation.ts

A branch for me to send various improvements I'm making over the weekend

Serge Improvements Aug 21

---

internal/explorer.point/src/components/subidentity/Subidentities.jsx
internal/explorer.point/src/components/subidentity/SubidentityRegistration.jsx
src/network/providers/ethereum.js

I have removed some unnecessary arguments that were passed around but not used, and I have fix an inconsistency in the treatment of subidentity registration params that was causing the registration to throw an error.
I have been able to successfully register a new subidentity with these changes.

Fix subidentity registration

---

src/name_service/identity.test.ts
src/name_service/identity.ts

Please refer to [the ticket](https://point-labs.atlassian.net/browse/PN-216) for context and an explanation on how to reproduce.

PN-216 Improve identity retrieval considering SNS and ENS

---

internal/explorer.point/src/pages/Wallet.jsx

Reword warning banner in wallet page

---

src/network/providers/ethereum.js

Fixes the deployment issues with the `Identity.json` not found in `zappdev` env.

Fix the zapp deployment issue in the zappdev env

---

.bash_alias
scripts/clean-local.sh
scripts/create-local-env.sh
src/api/server.ts
src/api/sockets/ZProxySocketController.js
src/client/proxy/middleware/auth.ts
src/util/getSecretToken.ts
src/util/index.ts

- Trim the token before calling verify
- Update the scripts to create the `token.txt` file with the token in the workspace directory
- Update the launch browser script to launch with the token in the URL

trim the secretToken string before calling verify

---

package-lock.json
package.json

We don't need React as a point node dependency

Remove React

---

internal/explorer.point/.eslintrc.js
internal/explorer.point/src/pages/Home.jsx
internal/explorer.point/src/pages/Identity.jsx
internal/explorer.point/src/pages/Wallet.jsx
internal/explorer.point/src/pages/Zapps.jsx

- Fix IKV table cell max width
- Remove timestamp from IKV table, as such a property doesn't exist and it always shows 1970-01-01
- Remove some unused code 
- Fixed eslint errors

React fixes

---

src/network/providers/solana.ts

Please refer to [the ticket](https://point-labs.atlassian.net/browse/PN-224) for context.

PN-224 Don't return 400 when SOL record doesn't have a POINT record

---

src/client/zweb/deployer/index.js
src/network/deployer/deployProxyImpl.ts
src/network/deployer/fetchOrDeploy.ts
src/network/deployer/forceImport.ts
src/network/deployer/index.ts
src/network/deployer/processProxyKind.ts
src/network/deployer/simulateDeploy.ts
src/network/deployer/upgradeProxy.ts

- Fixed blog deployment
- Restored and fixed upgrade proxy functionality

PD-300 Fix contract deployments

---

internal/explorer.point/src/components/wallet/SendModal.jsx

These changes allow users to use a _handle_ instead of a blockchain address as the beneficiary of a transfer in Wallet.

PN-273 Allow identities in wallet for token transfers

---

src/network/providers/solana.ts

I found two potential issues that can cause deployments to `.sol` domains to fail.
The first one is insufficient funds. Of course this is expected, the "surprising" part is how much funds are needed to create a record. Currently, the amount is 15479040 (0.01547904 SOL). So, if we get an error during the creation of the POINT record, the error message will ask users to please make sure they have enough funds.
The second issue is that writing to the POINT record immediately after creating it fails. The error message is not very descriptive unfortunately (_invalid account data for instruction_). However, I think it's safe to assume that the problem here is that the first transaction (record creation), is not yet fully confirmed when we send the second transaction (record update). I've added …

PN-295 Delay writing to POINT record after creation and improve error messages

---

internal/explorer.point/src/components/wallet/WalletRow.jsx

Adds missing wallet icons for mainnet, xnet, and solana_devnet.

Add missing wallet icons
