pointnetwork/pointnetwork

- scripts/deploy-sites.sh
Adding a warning when a Zapp has a package.json and not the folder node_modules. In this case the zapp developer should run npm install to install the dependencies before deploy the site.
> Warinig when a zapp has missing dependencies

- .env.e2e.example
- client/proxy/index.js
- docker-compose.e2e.yaml
Removed the `DEV_ZAPP_HOST` env var as a dependency so that `e2e` is more seamless for Zapp deployment and testing. Now there's no need to restart the environment while switching between Zapps and can now test multiple Zapps on the same go.
> Remove DEV_ZAPP_HOST to make deployment easier

- client/zweb/renderer/index.js
- internal/explorer.z/public/identity.zhtml
- network/web3bridge.js
Getting the IKVSet events of identity contract for the specific ZApp and matching with ikv elements in identity page. After that,  sorting and getting the last one. The timestamp is the block timestamp which the key value pair where inserted.
> Include last deployment timestamps to Point Explorer Identity meta data page

- example/pointsocial.z/contracts/PointSocial.sol
This PR fixes a bug where a user was previously able to add multiple likes to a post from the same identity. The solution was to add a check for that in the Solidity Contract and unlike the post if like button is pressed again.
[Trello card](https://trello.com/c/96ggvlgH/41-likes-on-pointsocialz-posts-need-to-be-counted-unique-by-identity)
> Fix/Likes on pointsocial.z posts need to be counted unique by identity

- client/storage/index-arweave.js
- client/storage/index.js
When uploading a file if the file was already created the original_path is not set to a temp one remaining the original filesystem path. This was crashing the ZApp access right after the deployment since arweave try to write the downloaded file to a path that does not exists or is not writable.
> Enforcing original_path to a temp one

- .bash_alias
Fixes the issue with tagging when we have `/` in our branch. Great StackOverflow resource [here](https://stackoverflow.com/questions/62905914/turning-a-git-branch-name-into-a-valid-docker-image-tag) for reference.
> Fix build-e2e script

- src/index.ts
When running inside the packaged version the configuration should be retrieved from the internal packaged config by default config library uses process.cwd() to reference the config folder.
When using vercel/pkg process.cwd references real folder and not packaged folder overwriting this env variable fixes the problems
> Use custom path config folder when running in pkg mode

- src/core/log.js
- src/core/utils.js
- src/index.ts
When ~ is provided as the datadir path.resolves concatenates it in the absolute path creating a bug:
suppose:
```
datadir = '~/a/b'
```
it resolves to:
```
/root/somedirectory/~/a/b
```
It should resolve to:
```
/user/home_directory/a/b
```
> Add util to resolve path when ~ is used

- docker-compose.zappdev.yaml
- src/client/storage/index-arlocal.js
Arlocal presented a bug for download chunks, [this one](https://github.com/textury/arlocal/issues/63). We bypassed the bug with a workarount to fetch chunks in another way. Now arlocal bug is fixed and we were able to remove the workaround. To test this PR is necessary to remove the image textury/arlocal and download it again from docker hub.
> removing arlocal workaround

- .github/workflows/pkg.yaml
- scripts/package-executables.sh
Add executable permissions.
Rename all executables to point
Use tar to compress the file in order to keep permissions and file name
> Improve build of executables pipeline

- Dockerfile
Changed docker file commands to better use cache and only rebuild the necessary commands when using buid-image --force script.
> PZ-33  Improve speed to rebuild local Docker Image using `build-image` script

- src/api/controllers/BlockchainController.ts
- src/client/proxy/handlers/common.ts
To keep things simple and avoid cross-origin requests, instead of Point SDK making requests to `https://web3.test`, it will make them to `${host}/v1/api/blockchain`.
This means that the Point Node proxy does not need any special logic to support the `https://web3.test` host.
> PN-114 Remove support for https://web3.test.

- src/client/proxy/handlers/common.ts
Redirect from .z to .point stop working after proxy refactoring, re-implementing it.
> Reimplement redirect from .z to .point

- config/default.yaml
- src/api/controllers/BlockchainController.ts
- src/api/index.js
- src/api/middleware/rpc-method-permission.ts
- src/api/sockets/ZProxySocketController.js
- src/client/proxy/handlers/common.ts
- src/network/blockchain.js
- src/permissions/PendingTxs.test.ts
- src/permissions/PendingTxs.ts
- src/permissions/types.ts
- src/rpc/rpc-handlers.ts
URL to connect to WS: `wss://point/ws?token=POINTSDK_TOKEN`.
- The auth token is a hardcoded string for now, there's not signature checks, it's just a string comparison. The expected token is set in config `api.sdk_auth_key`.
- I introduced a dedicated route for WS connections: `/ws`. The reason is that I wanted to include a _preValidation_ hook that would only affect the WS connections and not the REST API requests. But if you think this could introduce breaking changes, I can leave it as it was and find another way of using the _preValidation_ hook.
RPC requests can be made by sending messages with the `type: 'rpc'`, for example:
```javascript
// Get account balance
{
"type": "rpc",
"method": "eth_getBalance",
"params": ["0x916f8e7566dd63d7c444468cadea37e80f7f8048", "latest"]
}
// …
```
> PN-120 Handle RPC requests through WS and REST

- src/util/merkle.ts
Before refactoring utils the original function was:
```
return [].concat.apply([], levels);
```
Because apply takes an array as argument, it's flattening the result.
That chunk of code was replaced by:
```
return [...levels]
```
So if you console.log and compare the result of these functions you get this
```
{
usingDestructuring: [
[
<Buffer a6 dd 5f 01 96 0f 4e 47 72 cd 8b 2f 89 74 02 d2 01 db c1 d5 71 d0 8e 44 c2 56 e6 07 5a 94 2a 32>,
<Buffer 36 d3 c8 ea f9 47 10 91 db ab 4d 2c 1e d5 bd 6c 67 87 f5 5e 13 7c 38 31 e2 df d3 f9 93 f6 8b e3>
],
[
<Buffer 77 42 f5 70 f7 4b af 2e 65 d5 43 9f d0 24 34 4d 00 b6 01 40 7f 31 d1 b9 15 d8 b0 38 31 0b 1b 82>
]
],
usingConcantApply: [
<Buffer a6 dd 5f 01 96 0f 4e 47 72 cd 8b 2f 89 74 02 d2 01 db c1 d5 71 d0 8e 44 c2 56 e6 07 5a 94 2a 32>,
<Buffer 36 …
```
> Fix merkle function by flatting the returned array

- src/wallet/keystore.ts
With current configuration using require it's not possible to change the the keystore path for packaged app. This change addresses that issue.
> Read file rather than require in order to be able to specify a different keystore path

- package-lock.json
- package.json
Without these dependencies installed on the parent folder,
hardhat was throwing an error when running:
`point deploy <zapp> --contracts`.
Further details in this [Slack thread](https://point-labs.slack.com/archives/C02U1P7U4Q2/p1651230832849709).
If the `metamask-api` PR is merged before this one. I'll update this PR by installing dependencies with `npm 8`, so that it generates a _lockFileVersion 2_ instead of 1.
> Add missing hardhat dependencies

- src/client/storage/index.js
On first loading of a contract the variable chunkInfo is a buffer returned by getChunk function, but once the chunk is on our database that chunk is a string. So on first try to parse the chunkInfo it fails, but once the chunk is in the db it works ok. Parsing the string version solves the issue.
> Parse chunk converted to string rather than buffer

- .github/workflows/pkg.yaml
- .github/workflows/publish_release.yaml
The idea is that with these changes, the flow to release Point Node would be:
- tag a commit on `develop` branch -> triggers github action to create a _DRAFT_ release
- test the _DRAFT_ release
- merge `develop` into `master`
- push `master` -> triggers github action to publish the _DRAFT_ release
> PN-122 Add github action to publish release on push to `master`.

- hardhat/contracts/Identity.sol
Fixing a security problem found by running Slither.
References:
- (https://github.com/crytic/slither/wiki/Detector-Documentation#unprotected-upgradeable-contract).
- https://github.com/crytic/slither/issues/1029
> Fix unprotected initializer on upgradable contract.

- config/dockertest.yaml
- src/client/storage/index.js
- src/client/storage/storage.ts
The order in which chunks are retrieved is:
- local cache (sqlite)
- bundler's backup (S3)
- Arweave's cache
- Arweave's node(s)
I tested a few zApps with these changes (disabling local cache) and 100% of the chunks are coming from S3+Arweave cache:
- social.point
- 10 -> s3
- 32 -> arcache
- email.point
- 2 -> s3
- 2 -> arcache
- blog
- 18 arcache
I think the reason not all of them are coming from S3 is that "old" content is uploaded under a random string instead of chunkId. Maybe we could run a script that:
1. Downloads all files with a name that is 20 characters long (the random string ids)
2. Hashes the content
3. Checks if the hash from step 2 exists in S3, if it doesn't, re-upload the file with the hash as name
4. Delete the file from step 1 to save some space
But I wouldn't …
> PN-135 Fetch chunks from S3 before Arweave

- hardhat/contracts/Identity.sol
- src/api/controllers/IdentityController.js
Fix the problem of registering identities with capital letters.
> Convert identity to lower case before checking signature

- src/client/proxy/certificates.js
- src/client/proxy/handlers/common.ts
- tests/docker/proxy-storage.spec.js
SAN is a requirement for certs since 2016
But apparently it wasn't enforce for private root certs in Firefox, until now in v101 when it started to break
This fix should stop the warnings
> Add SubjectAltName to all generated domain certificates

- package.json
- src/client/proxy/handlers/common.ts
- src/name_service/registry.test.ts
- src/name_service/registry.ts
- src/name_service/types.ts
- src/network/providers/solana.ts
- src/util/index.ts
- src/util/parseCookieString.test.ts
- src/util/parseCookieString.ts
This is one part of the "Support SNS and ENS" feature. Here, we're adding support for `.sol` domains.
Proxy can understand and resolve `.sol` domains in two different ways:
1. The `.sol` domain has all the required information in its registry, the identity, the routes ID and the root directory ID. This option will only be available for sites that do not have smart contracts.
2. The `.sol` domain is an alias to a `.point` domain. In this case, the Solana domain registry only stores the point alias, and Proxy uses it to retrieve all the required information, as with any other `.point` domain.
[Here's an example of the first scenario](https://drive.google.com/file/d/1-Eg0dxdJ7p2MSCr5lwdk_E5-VHY42Yze/view?usp=sharing).
[And here's an example of the second …
> Add ability for proxy to resolve `.sol` domains

- src/api/controllers/PointSDKController.js
- src/api/index.js
- src/client/proxy/index.ts
- src/errors/index.ts
- src/errors/transformErrorResp.ts
Avoid propagating 5xx errors.
The most consistent and easiest way to do this that I found, without getting into a medium to large refactor, is to use Fastify's `onSend` hook to check and override error codes and messages.
I had to use `onSend` instead of other error-handling mechanisms provided by Fastify to be able to capture the situation where we explicitly call `res.status(5xx).send(...)`.
With these changes, we ensure that we do not send a 5xx error when an error is thrown, nor when `res.status(5xx).send(...)` is called.
I decided to override all 5xx errors, not just 500, as all errors in that range refer to "server errors". They are changed to 400. If you prefer a different status code, please let me know.
As potential improvement for the future, I think we could rely more on …
> Prevent showing 5xx server errors

- src/client/proxy/handlers/common.ts
- src/name_service/registry.test.ts
- src/name_service/registry.ts
- src/name_service/types.ts
- src/network/providers/ethereum.js
- src/network/providers/solana.ts
Works in the same way as SNS, but with a slight difference given the structure of Solana domains vs Ethereum domains.
In ENS, there are text records available, so, instead of storing the Point data in the `content`, we use a text record with a key of `point`.
There are two options:
1. have all the information in the ENS registry
2. have just an alias to a Point domain in the ENS registry
To test number 1, add a text record to your domain with a key of `point`, the value should be a Point identity, a routes ID and a root dir ID, in the following format: `pn_id=identity;pn_routes=hash-id-of-routes-file;pn_root=hash-id-of-root-dir-file`.
To test number 2, add a text record to your domain with a key of `point`, the value should be an alias to a Point identity, for example: …
> Add ability for proxy to resolve `.eth` domains

- src/@types/index.d.ts
- src/api/controllers/DeployController.js
- src/client/zweb/deployer/index.js
- src/core/deploy.js
- src/index.ts
Enable to use the option --force-deploy-proxy to force the replacement of the proxy on upgradable contracts deployment.
> Enable force-deploy-proxy option

- hardhat/hardhat.config.ts
Fix an error when try to start dev env without having a YNet key.
> Making dev env start without YNet key

- src/client/zweb/deployer/index.js
Store two new IKV entries when deploying a DApp. point.deploy.json should have these two entries to work:
`"pointSDKVersion": "version" ,
"pointNodeVersion": "version"`
> Store sdk and node version on deploy

- src/client/proxy/handlers/common.ts
- src/client/zweb/deployer/index.js
- src/network/providers/ethereum.js
Allows to use `@@copy_from_ikv=` directive in certain scenarios.
This is only enabled if in `blockchain.getKeyValue()` the argument `followCopyFromIkv` is set to true.
By default it is false, and only set to true in two places: when asking for the root directory (`::rootDir`) and routes file (`zdns/routes`)
When this feature is activated, `blockchain.getKeyValue()` doesn't just return the key result, but checks if it is a special directive prefixed with `@@copy_from_ikv=`, for instance: `@@copy_from_ikv=anotheridentity:somekeythere`. Then it parses the directive and tries to obtain ikv value for `somekeythere` from identity `anotheridentity`. This is not recursive.
If this succeeds, it returns this value instead.
This is a useful helper until we have proper UI and backend for software …
> Extend IKV with @@copy_from_ikv= instruction

- src/client/zweb/deployer/index.js
Changes:
1. Validate if the default signer of ethers is the same address of the wallet owner, if is not abort. Fix the bug of the deployer of a contract not be the wallet owner.
2. Fix bug of does not having deploy metadata or it being corrupted. Deployment process will restored metadata file from blockchain data by calling forceImport method.
3. Deployment of upgradable contract that verifies in the identity contract if the address is a deployer to allow upgrade. Example in point drive. If the contract don't has this feature yet the deploy will occur with a fallback call.
> DApps Deployment Improvement and fix.

- config/default.yaml
- src/network/providers/ethereum.js
The goal is to instantiate the web3 providers with the proper protocol and avoid errors such as calling Infura over http instead of https.
The bug in particular that we faced is that /wallet would not load and there were errors in the logs about RPC calls expected to be HTTPS. This was happening because The provider for Rinkeby was instantiated with HTTP instead of HTTPS.
I think that it could be a good idea to keep a `tls` field in the config, to tell whether a provider is supposed to work over HTTP/WS or HTTPS/WSS. So that we don't have to pass the protocol on every invocation. But there are many ways to go about it. And I'm not too familiar with the latest work on the wallet, so please feel free to change the solution.
> Add TLS information to blockchain providers

- src/client/proxy/handlers/common.ts
- src/client/proxy/httpsServer.ts
- src/client/proxy/middleware/cors.ts
- src/client/proxy/middleware/index.ts
Supporting CORS in proxy is needed to get assets from the `mirror`. Please refer to [the ticket](https://point-labs.atlassian.net/browse/PN-175) for further details.
CORS is only enabled for requests to mirror.point.
These changes only handle _simple_ requests. We may need to also support _preflight_ requests, but since I haven't came across them just yet, we could add support for them later on (however, if you want me to do it now, let me know).
> PN-175 Support CORS in proxy server

- src/network/providers/ethereum.js
I didn't replicate the error exactly, but, I replaced the [last two lines](https://github.com/pointnetwork/pointnetwork/blob/68e5da84a77339cd362371c170e760b6d3489fd6/src/network/providers/ethereum.js#L173-L174) of the modified function to use:
```
return new getWeb3().eth.Contract(abisByContractName[contractName], at)
```
instead of:
```
const web3 = getWeb3();
return new web3.eth.Contract(abisByContractName[contractName], at);
```
And I got the same error. So, it should be safe to follow the same approach in both cases: first `getWeb3()` and then call `new web3.eth.Contract`.
I also tested it by intentionally throwing [here](https://github.com/pointnetwork/pointnetwork/blob/68e5da84a77339cd362371c170e760b6d3489fd6/src/network/providers/ethereum.js#L140).
> PF-22 Create instance of `eth.Contract` properly

- scripts/create-local-env.sh
Running using git bash, I needed to ad ts-node dependency as global and also adjust the home path to windows format. After that the dev environment could be started on windows.
> Fix path and dependency on windows

- src/client/proxy/certificates.ts
Trying to solve this error msg by changing serialNumber hash from md5 to sha256. Needs to be verified in the environment where the msg occurred.
> PZ-78 ca md certificate too weak

- .bash_alias
- package.json
- point
Allow the deployment of DApps from the DApp folder. For running use:
`point-deploy --contracts`
The folder parameter is not needed since the current folder is considered as the deployment folder.
Also can use as usual from pointnetwork folder
`point-deploy ../dapp_folder --contracts`
> Deploy from dapp folder

- package-lock.json
- package.json
- src/api/controllers/IdentityController.js
- src/wallet/keystore.ts
Please refer to ticket [PN-197](https://point-labs.atlassian.net/browse/PN-197) for context.
With these changes, the Solana account derived by Point Engine matches the default one derived by Phantom Wallet given the same secret phrase:
**WARNING**: merging this would mean "changing" Solana accounts of existing users, as we will derive different ones from their existing secret phrases. I think this is fine in ynet and that the sooner we change it the better, but let's please analyse carefully.
> PN-197 Derive Solana keypairs same as Phantom Wallet

- package-lock.json
- package.json
- src/api/sockets/ZProxySocketController.js
- src/rpc/decode.test.ts
- src/rpc/decode.ts
- src/rpc/rpc-handlers.ts
If the RPC request to `sendTransaction` includes information about which Smart Contract it wants to call, Point Engine will fetch the ABI, decode the transaction input data and added to the response, so that clients can display human-readable information to users.
In order not to introduce any breaking changes, if the contract information is not provided, the response is the same as it was before.
Also to maintain backwards compatibility, the decoded data is added as a new key in the payload.
> PN-200 Decode tx input data

- config/default.yaml
- src/client/proxy/handlers/common.ts
- src/client/zweb/deployer/index.js
- src/name_service/registry.test.ts
- src/name_service/registry.ts
- src/util/cookieString.test.ts
- src/util/cookieString.ts
The main goal is to allow the deployment of simple sites (no smart contracts) to `.sol` and `.eth` targets.
Please refer to [this video](https://drive.google.com/file/d/1SJ1thzmtoHEh-mo8N5uoZkm8z-Ni1ttA/view?usp=sharing) for a quick demo and to [the ticket](https://point-labs.atlassian.net/browse/PN-199) for context.
> PN-199 Allow deployment of SNS/ENS without a Point Identity

- src/network/providers/ethereum.js
This PR addresses two things:
1. A stupid mistake I made, using `has` instead of `get` to grab a value from config.
2. Explicitly set `gasPrice`  on txs that we process through the RPC handler.
I liked a post, wrote a comment and sent an email and the tx fees are very low, as expected.
> Make sure gasPrice is set as per the config value

- package.json
- src/network/providers/ethereum.js
Increase speed of querying for events due small parallel request to try to solve PZ-412. However, it seems that the query for events is becoming much slower when the number of blocks increase. This solution make the interface works, but takes a long time to load.
> Pagination of events query

- config/default.yaml
- src/client/proxy/handlers/common.ts
- src/client/proxy/handlers/mirror.ts
- src/client/proxy/middleware/cors.ts
- src/client/proxy/proxyUtils.ts
- src/client/storage/config.ts
- src/client/storage/init/init.zappdev.ts
- src/client/zweb/renderer/index.js
This is an update from Aug 7, so needs to be merged properly
- a few bugfixes to renderer (a bunch of returns and awaits were missing, so zhtml error messages weren't properly propagating to the browser), AR mint not reading the environment mode properly
- add throw tag into zhtml {% throw 'anything' %} will throw 'anything' as an error, instead of using a bunch of multi-nested ifs in zhtml logic
- two new web2 domain redirects with CORS enabled: fonts.googleapis.com -> gfonts.mirror.point, fonts.gstatic.com -> gfontfiles.mirror.point
While it's being merged, I'll try to upload the mirrors content and we can test whether we now have fully web3 copy of Google Fonts perfectly working
Upd: +if there is a .local domain, it tries to resolve it using zappsdir even in production mode. That was a …
> Serge improvements aug 7

- src/client/proxy/handlers/pointApi.ts
Comment out the route that was ultimately invoking hardhat, which does not work inside the `pkg` binary as it looks for _hardhat.config.js_ in the OS FS and not the virtual FS.
> Comment out deploy route

- src/name_service/identity-cache.test.ts
- src/name_service/identity-cache.ts
- src/name_service/identity.ts
- src/name_service/types.ts
- src/rpc/decode.test.ts
We call SNS/ENS to check if ethereum and solana accounts have domains associated to them. We do this when getting identities and wallet information, which can result in large delays for users, and an overuse of services such as Infura.
This PR can be merged as is, but as an additional improvement, I have opened PR #564 against this branch. Please check it out and let me know your thoughts.
> PN-211 Add an identity cache to avoid overcalling SNS/ENS

- src/api/controllers/WalletController.js
Timeouts have been adding to the requests to resolve SNS/ENS domains. When an error occurs, we send the string `Error` as the alias, which causes the UI to render `Error` as the wallet address.
I think a better approach is to send an empty string. The UI is prepared to handle this, it will fallback to rendering the blockchain address.
> Send empty `alias` when SNS/ENS times out

- src/core/index.ts
Switching off background job to fetch events since we have stopped using them in Point Explorer.
> Remove background job to fetch events

- internal/explorer.point/package.json
- package-lock.json
- package.json
- src/api/controllers/Web2Controller.js
- tests/api/web2Controller.spec.js
- Fixed the web2 links not opening by commenting out a line of code (didn't knew if it might be useful later on so commented it)
- Removed redundant `point-contract-manager` package from the root `package.json` 
- Installed `cross-env` for cross platform compatibility in the root `package.json` and updated & tested `scripts`
- Fixed the `clear` script in `internal/explorer.point/package.json`. The earlier script would create a `-p` directory and fail to delete the `public` directory. Now it works fine - tested on Windows using git-bash. Please test on other systems as well.
> Fix the Point Browser not opening web2 links

- src/api/controllers/IdentityController.js
- src/name_service/identity-cache.test.ts
- src/name_service/identity-cache.ts
- tests/api/walletController.spec.js
When a new identity is registered, we don't want to wait until the previous cache entry expires, as this results in the user having to wait until expiration to be able to use Point Explorer as intended.
To fix it, as soon as a new identity is registered, we overwrite the previous entry in the cache.
> PN-218 add to identity cache upon registration

- src/client/proxy/handlers/common.ts
With this, the TLD part of a subidentity will not be treated as an unknown file extension and the proxy will render `text/html`.
> Return correct contentType for subidentities

- config/default.yaml
As requested, this reduces the upload loop interval to speed up the deployment process.
In my tests, I see:
* upload_loop_interval: 2000 ->  57631 ms
* upload_loop_interval: 100   ->  34557 ms
> Reduce upload loop interval

- package-lock.json
- src/api/api_routes.js
- src/network/providers/solana.ts
There's a new `POINT` record available on Solana Domain Registries, so, instead of writing Point Network data to the main content of the registry, we will use the `POINT` record.
These changes are not backwards compatible in that we don't check for existing data in the main domain content. We could, but I figured nobody was using _.sol_ domains to make deployments yet. So I decided to keep the implementation as simple as possible. But please let me know if you think it's important for us to also support the older implementation.
I had to unprotect the endpoint ` /v1/api/identity/resolve/:domain`, this is called by the Engine, not by Point SDK.
> PN-217 Use `POINT` record of Solana Domain Registry

- config/development.yaml
Without this change, point explorer is bound to `mainnet`, which is of no use for development.
Of course, it can be overridden by `local-development` config, but IMO it makes sense to use `xnet` by default in development.
> Set xnet as a default network for development

- internal/explorer.point/src/components/LinkPointToSol.jsx
- internal/explorer.point/src/pages/Home.jsx
- src/api/api_routes.js
- src/api/controllers/IdentityController.js
- src/name_service/registry.test.ts
- src/name_service/registry.ts
- src/name_service/types.ts
- src/network/providers/solana.ts
- src/rpc/rpc-handlers.ts
- src/util/cookieString.test.ts
- src/util/cookieString.ts
- tests/api/identityController.spec.js
Please refer to [the ticket](https://point-labs.atlassian.net/browse/PN-223) for context.
The `identityToOwner` response has a new `pointAddress` key.
- If the identity is _.point_, `pointAddress` will be the same as `owner`.
- if the identity is _.sol_, `pontAddress` will be the Point Address of the current user, and `owner` will be the Solana address that owns the .sol domain.
- if the identity is _.eth_, `pointAddress` will be the same as `owner`, and will refer to the Ethereum address that owns the .eth domain.
It was implemented like this to keep the `owner` key as it was, and avoid breaking changes.
The homepage of Point Explorer shows a recommendation to SOL domain owners to "link" their POINT address. In practice, this means writing the Point Address to the `POINT` record of the …
> PN-223 sol to point

- internal/explorer.point/src/components/LinkPointToSol.jsx
- internal/explorer.point/src/components/PointAddressRow.jsx
- internal/explorer.point/src/hooks/useLinkPointToSol.js
- internal/explorer.point/src/pages/Identity.jsx
These changes add a row to the table that is displayed in the Identity page. This additional row is only displayed when dealing with a `.sol` identity, since the `owner` of such identities is a Solana address and not a Point one.
This is what it looks like in four different scenarios.
Owner seeing their own identity, before linking their Point address:
Owner seeing their own identity, after having linked their Point address:
Visitor seeing a `.sol` identity that does not have a Point address linked to it:
Visitor seeing a `.sol` identity that has a Point address linked to it:
> PN-226 Add Point Address to Identity page of SOL domains

- src/api/controllers/IdentityController.js
In order to be able to integrate `.sol` identities into dApps such as `email.point`, we need the ability to retrieve the Point Public Key associated to a `.sol` domain, for encryption purposes.
> PZ-469 Lookup Point public key of .sol identity

- internal/explorer.point/src/pages/MyIdentities.jsx
Since `.sol` identities cannot register subidentities, I think the best approach is to simply hide the **Sub-Identies** section of _myidentities_ page.
> PN-239 Don't show subidentities for SOL domains

- internal/explorer.point/src/components/PublicKeyRow.jsx
- internal/explorer.point/src/pages/Identity.jsx
Owner of a `.sol` domain that has not been linked yet:
Owner of a `.sol` domain that has linked the Point Address:
Visitor seeing a "linked" `.sol` identity:
Visitor seeing a "not linked" `.sol` identity:
> PN-240 Improve display of public key for .sol identities

- internal/explorer.point/src/App.js
- internal/explorer.point/src/custom.css
- internal/explorer.point/src/pages/Identity.jsx
`.sol` owners will see a link-button next to their handle in their identity page that will redirect them to the "registration" page, where they can register a `.point` identity.
Once done, the `.point` identity will take precedence over the `.sol` one.
> PN-242 Let .sol owners create .point identity

- src/client/proxy/handlers/common.ts
- src/client/proxy/proxyUtils.ts
The idea:
- In the static handler, we first detect content type, using the lib. If it's detected as `text/plain`, we look at the extension, to handle `css` and `js`. Previously, we were first relying on the extension, so the content-type could be spoofed by malicious website.
- In HTML handler I've removed detection by extension and always return `text/html` instead, as it doesn't make sense.
I've tested explorer, social, email, created blog and drive, everything is working.
> Change content type detection way

- src/network/providers/ethereum.js
- src/rpc/decode.ts
- src/rpc/rpc-handlers.ts
These changes add a gas estimate to the _decoded tx input_ that is returned when a transaction is stored for confirmation. Point SDK can use the additional gas information to show it in the Confirmation Window.
To keep it flexible, a `gas.currency` field has been added. Generally speaking, I think it should always be POINT, but this is useful to show gas estimate of other ad-hoc transactions, like dealing with SNS.
> PN-257 Add gas estimate to Txs

- internal/explorer.point/src/components/wallet/TokenRow.jsx
- src/wallet/index.ts
These changes fix the bug described in [the ticket](https://point-labs.atlassian.net/browse/PN-259). And help Point SDK provide more details about the transfer by returning the `value`. To see how this is used in the confirmation window, please refer to [this PR](https://github.com/pointnetwork/pointsdk/pull/79).
> PN-259 Fix bug in ERC20 token transfer

- config/default.yaml
- src/client/storage/index.ts
- src/network/providers/ethereum.js
- src/rpc/decode.ts
- src/rpc/rpc-handlers.ts
These changes add some metadata to the transaction inputs, which is attached to the response that Point Engine sends when a transaction is stored for user confirmation.
The caller,  Point SDK, can use this additional metadata to enrich the information presented to the user in the confirmation window.
The metadata these changes add is related to inputs that look like storage IDs and empty hashes (_0x000..._).
- For an empty hash, it will simply return a "no_content" message.
- If the hash refers to a file on disk, a message indicating that it's a storage ID is returned.
- If the hash refers to a blockchain transaction hash for which a receipt can be fetched successfully, a message indicating it's a tx hash is returned.
- If the two checks above fail, a "not found" message is returned.
> PN-262 Add metadata to decoded tx input

- src/rpc/decode.ts
- src/wallet/index.ts
This PR implements two changes related to identities:
1. If one of the inputs of a transaction is an address, Point Engine will try to resolve it to an identity and it will attach some additional metadata to the response, so that Point SDK can present it in the confirmation window.
2. If the transaction is a token transfer, Point Engine will return the beneficiary address to Point SDK, so that it can present this information to the user in the confirmation window.
> PN-265 Add identity metadata to transactions

- scripts/create-local-env.sh
- scripts/start-local.sh
Running the bash alias `point-dev-install` was running `npx harhdat compile` in `point-contracts`, instead of `npm run build`. Currently, `npm run build` includes a workaround to an error we were getting related to not generating `typechain` directory in `point-contracts`.
> Running npm run build instead of npx hardhat compile.

- config/development.yaml
- config/devlocal.yaml
- config/gateway.yaml
- config/production.yaml
- config/visitlocal.yaml
Please refer to [the ticket](https://point-labs.atlassian.net/browse/PN-256) for more details. In summary, public RPC providers such as `api.mainnet-beta.solana.com` have very restrictive limits as they are not meant for production use. The reserve the right of changing the limits and even block clients without prior notice.
They apply limits per RPC method, which would explain why some calls succeeded while other failed.
A quick workaround is to change to another provider, which is exactly what this PR is doing. Long term, we might want to consider private providers.
> PN-256 Change Solana RPC provider

- config/default.yaml
- src/network/providers/ethereum.js
- src/network/providers/solana.ts
In general, the idea is to be able to disable and enable _problematic/fragile_ functionality from a single place.
In particular, these changes add a few configuration variables to toggle name services on or off. Name services are particularly fragile because they depend on providers for Ethereum and Solana and we are not using providers with strong SLAs. Therefore, I think it makes sense to wrap this functionality in feature flags.
For **ENS**, I'm disabling it as it will not work until we migrate away from Rinkeby.
For **SNS**, I'm leaving it enabled because with the change in RPC provider ([this PR](https://github.com/pointnetwork/pointnetwork/pull/733)), it works. Also, for SNS, we have two flags, one to control the entire feature, and another one to control just the `getAllDomains` …
> PN-269 Add feature flags to toggle name services on/off

- src/rpc/decode.ts
When decoding transactions, if we find an _address_, we try to resolve it to a _handle_, and attach that _handle_ as part of the decoded transaction metadata.
With these changes, in addition to the _handle_, we also attach the _address_ in the metadata, so that it can be easily consumable in Point SDK.
> PN-276 Add address to identity metadata

- src/api/api_routes.js
- src/api/controllers/ContractController.js
The new endpoint `/v1/api/contract/listEvents/:identity` allows us to get a list of smart contract events implemented by a dApp.
If the dApp has deployed several contracts, we look for events in all of them, keeping a reference of which contract the events belong to.
If the dApp has not deployed any contracts, it will simply return an empty array.
For example:
```
GET /v1/api/contract/listEvents/social
"data": [
{
"contractName": "PointSocial",
"events": [
"AdminChanged",
"BeaconUpgraded",
"OwnershipTransferred",
"ProfileChange",
"StateChange",
"Upgraded"
]
}
]
```
> PN-272 Add endpoint to get list of events by dApp

- src/client/zweb/deployer/index.js
Fix bugs in deployer:
- Unresolved variable `deployConfigFilePath` is used
- `isNewBaseVersionValid` is broken: it expects `major.minor` in one place and then `major.minor.patch` in another
> PN-284 Fix bugs in deployer

- src/network/providers/keplr.ts
- src/rpc/rpc-handlers.ts
These changes introduce the basic flow to _intercept_ some calls to the Keplr client and trigger the confirmation window flow.
I have also made a small refactor so that the implementation is a bit more aligned with Ethereum's and Solana's.
It's just a suggestion because the Keplr integration (or maybe I should say the Cosmos integration) is different, so it's not clear to me if it makes sense to try to align to Ethereum and Solana. For example, if a lot of methods are going to require user confirmation and payloads are too different, this approach could be more verbose. But for now, I think it helps.
> Request confirmation for keplr's sendTx

- config/default.yaml
- src/client/proxy/handlers/common.ts
ping-pub makes requests to our blockchain node directly. So, these changes allow such requests.
I added two config variables:
- `cosmos_node_api_url` is the hardcoded URL on ping-pub's side. All requests to the blockchain node are made to this base URL.
- `ping_pub_identity` is the identity to which ping-pub has been deployed (for now only in _xnet_). It is used to allow CORS.
> PN-278 Allow requests to Point Network Blockchain Node

- src/network/providers/solana.ts
A quick and dirty retry if SNS deployment fails due to the record not being created yet when we try to write to it.
> Retry SNS deployment
